spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: 123456
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.type: true
      hibernate.use_sql_comments: true
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      properties:
        offsets.topic.replication.factor: 1
        transaction.state.log.replication.factor: 1
        transaction.state.log.min.isr: 1
    topic:
      payment-transactions: payment-transactions-topic
    consumer:
      group-id: payment-transaction-group
